// Example:
// export const TYPE = "TYPE";

export const CHANGE_NAV_STATE = "CHANGE_NAV_STATE"

export const UPDATE_GRAPH_DIMENSIONS = "UPDATE_GRAPH_DIMENSIONS"

export const SEARCH = "SEARCH"

export const UPDATE_GRAPH = "UPDATE_GRAPH"
export const UPDATE_INFO_PANE = "UPDATE_INFO_PANE";

export const UPDATE_TRAINING_DATA = "UPDATE_TRAINING_DATA"
export const UPDATE_EVENT_GRAPH = "UPDATE_EVENT_GRAPH";